key_name             = "cmtr-s5mse3rq-keypair"
instance_name        = "cmtr-s5mse3rq-ec2"
existing_vpc_name    = "cmtr-s5mse3rq-vpc"
existing_sg_name     = "cmtr-s5mse3rq-sg"
existing_subnet_cidr = "10.0.1.0/24"
